// <auto-generated />
namespace AddressMaintenance.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MadeValidFromfieldnotnull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MadeValidFromfieldnotnull));
        
        string IMigrationMetadata.Id
        {
            get { return "201711131033357_Made ValidFrom field not null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
