// <auto-generated />
namespace AddressMaintenance.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Tweakedrequiredvalues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tweakedrequiredvalues));
        
        string IMigrationMetadata.Id
        {
            get { return "201711111604283_Tweaked required values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
